- hosts: all
  become: true
  vars:
    pg_conf: /var/lib/pgsql/data/postgresql.conf
    hba_conf: /var/lib/pgsql/data/pg_hba.conf
  tasks:
    - name: Установка PostgreSQL
      shell: |
        if [ -f /etc/debian_version ]; then
          apt update && apt install -y postgresql
        elif [ -f /etc/redhat-release ]; then
          dnf install -y postgresql-server postgresql-contrib
          postgresql-setup --initdb
          systemctl enable postgresql
        fi

    - name: Включаем внешний доступ
      copy:
        src: templates/postgresql.conf.j2
        dest: "{{ pg_conf }}"
      notify: Перезапуск PostgreSQL

    - name: Настраиваем доступ по IP
      copy:
        src: templates/pg_hba.conf.j2
        dest: "{{ hba_conf }}"
      notify: Перезапуск PostgreSQL

    - name: Запускаем PostgreSQL
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Создаём пользователя student
      become_user: postgres
      shell: psql -c "CREATE USER student WITH PASSWORD 'student';"

  handlers:
    - name: Перезапуск PostgreSQL
      service:
        name: postgresql
        state: restarted